# Generated by Django 5.1.6 on 2025-03-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsfetch', '0004_job_qualification_job_responsibilities'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='jobid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Jobsfetch.job'),
            preserve_default=False,
        ),
    ]
