# Generated by Django 5.1.6 on 2025-03-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsfetch', '0004_job_qualification_job_responsibilities'),
        ('chatbot', '0002_chatsession_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='jobid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobsfetch.job'),
        ),
    ]
