# Generated by Django 5.1.6 on 2025-02-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_registration_last_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
