# Generated by Django 5.1.6 on 2025-03-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsfetch', '0004_job_qualification_job_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(default=''),
        ),
    ]
