# Generated by Django 5.1.6 on 2025-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsfetch', '0005_alter_jobapplication_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
